using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Enigma.Core.Asymmetric.Pqc;
using Enigma.Core.Asymmetric.PublicKey;
using Enigma.Core.Hashing.Hmac;
using Enigma.DataEncryption.Internal;

namespace Enigma.DataEncryption.UnitTests.Internal;

/// <summary>
/// The five header shapes of <c>docs/format.md</c> §3, and the fixed inputs the golden vectors are
/// built from.
/// </summary>
/// <remarks>
/// Every input here is deterministic so that a header written from it is byte-for-byte reproducible.
/// The arrays are returned from methods rather than exposed as fields: the production code clears key
/// material in place, so a shared array would be zeroed out from under the next test.
/// </remarks>
internal static class FormatTestData
{
    /// <summary>Wrapped-key length used for the RSA shape — an RSA-2048 modulus.</summary>
    internal const int RsaWrappedKeyLength = 256;

    /// <summary>Encapsulation length used for the ML-KEM shape — ML-KEM-512.</summary>
    internal const int MLKemEncapsulationLength = 768;

    /// <summary>
    /// The ML-KEM parameter set the <see cref="HeaderShape.MLKem"/> and <see cref="HeaderShape.Hybrid"/>
    /// fixtures use.
    /// </summary>
    internal const MLKemParameterSet MLKemFixtureParameterSet = MLKemParameterSet.MLKem512;

    /// <summary>The OAEP hash the <see cref="HeaderShape.Rsa"/> fixture records at offset 5.</summary>
    /// <remarks>
    /// The default, so the shape stays the one a caller who selects nothing produces. The suites that
    /// care about the <i>other</i> two values sweep them explicitly.
    /// </remarks>
    internal const RsaOaepHash RsaFixtureOaepHash = RsaOaepHash.Sha256;

    /// <summary>
    /// Every header shape, so a suite that must hold for all of them says so once rather than listing
    /// them — which is what let method <c>0x05</c> be added without hunting for the lists that had
    /// enumerated four.
    /// </summary>
    internal static HeaderShape[] AllShapes =>
        [HeaderShape.Pbkdf2, HeaderShape.Argon2, HeaderShape.Rsa, HeaderShape.MLKem, HeaderShape.Hybrid];

    /// <summary>The fixed 32-byte data key <c>K</c>: bytes <c>00</c>–<c>1F</c>.</summary>
    internal static byte[] DataKey() => Sequence(0x00, DataEncryptionDefaults.DataKeySizeBytes);

    /// <summary>The fixed 12-byte GCM nonce: bytes <c>00</c>–<c>0B</c>.</summary>
    internal static byte[] Nonce() => Sequence(0x00, DataEncryptionDefaults.NonceSizeBytes);

    /// <summary>The fixed 16-byte KDF salt: bytes <c>10</c>–<c>1F</c>.</summary>
    internal static byte[] Salt() => Sequence(0x10, DataEncryptionDefaults.SaltSizeBytes);

    /// <summary>Stand-in wrapped-key bytes. PHASE01 needs a field of the right length, not real OAEP output.</summary>
    internal static byte[] WrappedKey() => Sequence(0x40, RsaWrappedKeyLength);

    /// <summary>Stand-in encapsulation bytes, for the same reason as <see cref="WrappedKey"/>.</summary>
    internal static byte[] Encapsulation() => Sequence(0x80, MLKemEncapsulationLength);

    /// <summary>A fresh HMAC-SHA256 service.</summary>
    internal static IHmacService HmacSha256() => new HmacServiceFactory().CreateHmacSha256Service();

    /// <summary>Builds a byte array of <paramref name="length"/> bytes counting up from <paramref name="start"/>.</summary>
    /// <param name="start">The first value; the sequence wraps at 256.</param>
    /// <param name="length">The number of bytes.</param>
    /// <returns>The generated bytes.</returns>
    internal static byte[] Sequence(int start, int length)
    {
        byte[] bytes = new byte[length];
        for (int i = 0; i < length; i++)
        {
            bytes[i] = (byte)(start + i);
        }

        return bytes;
    }

    /// <summary>The total header length of a shape, per <c>docs/format.md</c> §3.</summary>
    /// <param name="shape">The header shape.</param>
    /// <returns>The header length in bytes.</returns>
    internal static int HeaderLengthOf(HeaderShape shape) => shape switch
    {
        HeaderShape.Pbkdf2 => FormatLayout.Pbkdf2HeaderLength,
        HeaderShape.Argon2 => FormatLayout.Argon2HeaderLength,
        HeaderShape.Rsa => FormatLayout.RsaHeaderBaseLength + RsaWrappedKeyLength,
        HeaderShape.Hybrid =>
            FormatLayout.HybridHeaderBaseLength + RsaWrappedKeyLength + MLKemEncapsulationLength,
        _ => FormatLayout.MLKemHeaderBaseLength + MLKemEncapsulationLength,
    };

    /// <summary>The <see cref="EncryptionMethod"/> a shape corresponds to.</summary>
    /// <param name="shape">The header shape.</param>
    /// <returns>The method byte's enum value.</returns>
    internal static EncryptionMethod MethodOf(HeaderShape shape) => shape switch
    {
        HeaderShape.Pbkdf2 => EncryptionMethod.Pbkdf2,
        HeaderShape.Argon2 => EncryptionMethod.Argon2,
        HeaderShape.Rsa => EncryptionMethod.Rsa,
        HeaderShape.Hybrid => EncryptionMethod.Hybrid,
        _ => EncryptionMethod.MLKem,
    };

    /// <summary>
    /// Writes the header for a shape, from the fixed inputs above, and returns the bytes written.
    /// </summary>
    /// <param name="shape">The header shape to write.</param>
    /// <param name="cipher">The cipher byte to record.</param>
    /// <returns>The complete header bytes — the GCM associated data.</returns>
    internal static async Task<byte[]> BuildHeaderAsync(HeaderShape shape, Cipher cipher = Cipher.Aes256Gcm)
    {
        using MemoryStream output = new();
        byte[] header = await WriteHeaderAsync(output, shape, cipher).ConfigureAwait(false);

        // What the writer returned and what it wrote must be the same bytes; every other test in this
        // folder leans on that, so assert it at the source.
        if (!AreEqual(header, output.ToArray()))
        {
            throw new InvalidOperationException("HeaderWriter returned bytes that differ from what it wrote.");
        }

        return header;
    }

    /// <summary>Writes the header for a shape to <paramref name="output"/>.</summary>
    /// <param name="output">The destination stream.</param>
    /// <param name="shape">The header shape to write.</param>
    /// <param name="cipher">The cipher byte to record.</param>
    /// <returns>The complete header bytes — the GCM associated data.</returns>
    internal static Task<byte[]> WriteHeaderAsync(
        Stream output,
        HeaderShape shape,
        Cipher cipher = Cipher.Aes256Gcm) => shape switch
    {
        HeaderShape.Pbkdf2 => HeaderWriter.WritePbkdf2HeaderAsync(
            output, cipher, Nonce(), Salt(), DataEncryptionDefaults.Pbkdf2Iterations,
            DataKey(), HmacSha256(), CancellationToken.None),

        HeaderShape.Argon2 => HeaderWriter.WriteArgon2HeaderAsync(
            output, cipher, Nonce(), Salt(), DataEncryptionDefaults.Argon2Iterations,
            DataEncryptionDefaults.Argon2DegreeOfParallelism, DataEncryptionDefaults.Argon2MemorySizeKb,
            DataKey(), HmacSha256(), CancellationToken.None),

        HeaderShape.Rsa => HeaderWriter.WriteRsaHeaderAsync(
            output, cipher, RsaFixtureOaepHash, Nonce(), WrappedKey(), DataKey(), HmacSha256(),
            CancellationToken.None),

        // The hybrid's DataKey() stands in for the combiner's output, which PHASE01-style header tests do
        // not need to be real: HeaderWriter takes the combined key as an opaque 32 bytes, and whether it
        // really is HybridKeyCombiner's output is what HybridGoldenVectorTests pins.
        HeaderShape.Hybrid => HeaderWriter.WriteHybridHeaderAsync(
            output, cipher, MLKemFixtureParameterSet, Nonce(), WrappedKey(), Encapsulation(),
            DataKey(), HmacSha256(), CancellationToken.None),

        _ => HeaderWriter.WriteMLKemHeaderAsync(
            output, cipher, MLKemFixtureParameterSet, Nonce(), Encapsulation(),
            DataKey(), HmacSha256(), CancellationToken.None),
    };

    /// <summary>Parses a header from a byte array.</summary>
    /// <param name="header">The container bytes, starting at the magic.</param>
    /// <param name="expectedMethod">The method the caller claims to read, or <see langword="null"/> for any.</param>
    /// <param name="limits">The bounds to apply; <see langword="null"/> uses the defaults.</param>
    /// <returns>The parsed header.</returns>
    internal static Task<ParsedHeader> ReadHeaderAsync(
        byte[] header,
        EncryptionMethod? expectedMethod = null,
        DataEncryptionLimits? limits = null)
    {
        MemoryStream input = new(header, writable: false);
        return HeaderReader.ReadAsync(
            input, expectedMethod, limits ?? DataEncryptionLimits.Default, CancellationToken.None);
    }

    /// <summary>Returns a copy of <paramref name="source"/> with one byte replaced.</summary>
    /// <param name="source">The original bytes.</param>
    /// <param name="offset">The offset to overwrite.</param>
    /// <param name="value">The replacement byte.</param>
    /// <returns>The patched copy.</returns>
    internal static byte[] WithByteAt(byte[] source, int offset, byte value)
    {
        byte[] patched = (byte[])source.Clone();
        patched[offset] = value;
        return patched;
    }

    /// <summary>
    /// Returns a copy of <paramref name="source"/> with a signed 32-bit little-endian value written at
    /// an offset.
    /// </summary>
    /// <param name="source">The original bytes.</param>
    /// <param name="offset">The offset of the 4-byte field.</param>
    /// <param name="value">The value to encode.</param>
    /// <returns>The patched copy.</returns>
    internal static byte[] WithInt32At(byte[] source, int offset, int value)
    {
        byte[] patched = (byte[])source.Clone();
        patched[offset] = (byte)value;
        patched[offset + 1] = (byte)(value >> 8);
        patched[offset + 2] = (byte)(value >> 16);
        patched[offset + 3] = (byte)(value >> 24);
        return patched;
    }

    /// <summary>Returns a copy of <paramref name="source"/> with the bit at <paramref name="bitIndex"/> flipped.</summary>
    /// <param name="source">The original bytes.</param>
    /// <param name="bitIndex">The zero-based bit index across the whole array.</param>
    /// <returns>The patched copy.</returns>
    internal static byte[] WithFlippedBit(byte[] source, int bitIndex)
    {
        byte[] patched = (byte[])source.Clone();
        patched[bitIndex / 8] ^= (byte)(1 << (bitIndex % 8));
        return patched;
    }

    private static bool AreEqual(byte[] left, byte[] right)
    {
        if (left.Length != right.Length) return false;

        for (int i = 0; i < left.Length; i++)
        {
            if (left[i] != right[i]) return false;
        }

        return true;
    }
}
